version: '3.8'

services:
  server:
    container_name: lift_server
    restart: always
    network_mode: "host"
    build:
      context: .
      args:
        - db_user=$DB_USER
        - db_password=$DB_PASSWORD
        - db_host=127.0.0.1
      dockerfile: Dockerfile
    depends_on:
      - psql_db
  
  psql_db:
    container_name: lift_db
    build:
      context: db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - '5432:5432'
    volumes:
      - db-data:/data/db

volumes:
  db-data: