// Code generated by "enumer -type=State -transform=snake -output=state_string.go -linecomment=true"; DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
)

const _StateName = "runningpendingstopped"

var _StateIndex = [...]uint8{0, 7, 14, 21}

const _StateLowerName = "runningpendingstopped"

func (i State) String() string {
	i -= 2
	if i >= State(len(_StateIndex)-1) {
		return fmt.Sprintf("State(%d)", i+2)
	}
	return _StateName[_StateIndex[i]:_StateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StateNoOp() {
	var x [1]struct{}
	_ = x[Running-(2)]
	_ = x[Pending-(3)]
	_ = x[Stopped-(4)]
}

var _StateValues = []State{Running, Pending, Stopped}

var _StateNameToValueMap = map[string]State{
	_StateName[0:7]:        Running,
	_StateLowerName[0:7]:   Running,
	_StateName[7:14]:       Pending,
	_StateLowerName[7:14]:  Pending,
	_StateName[14:21]:      Stopped,
	_StateLowerName[14:21]: Stopped,
}

var _StateNames = []string{
	_StateName[0:7],
	_StateName[7:14],
	_StateName[14:21],
}

// StateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StateString(s string) (State, error) {
	if val, ok := _StateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to State values", s)
}

// StateValues returns all values of the enum
func StateValues() []State {
	return _StateValues
}

// StateStrings returns a slice of all String values of the enum
func StateStrings() []string {
	strs := make([]string, len(_StateNames))
	copy(strs, _StateNames)
	return strs
}

// IsAState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i State) IsAState() bool {
	for _, v := range _StateValues {
		if i == v {
			return true
		}
	}
	return false
}
