type Configuration {
  usecases: [UseCaseConfiguration!]!
}

type UseCaseConfiguration {
  name: String!
  services: [ServiceConfiguration!]!
}

type ServiceConfiguration {
  type: ServiceType!
  version: String!
  plugins: [PluginConfiguration!]!
}

type PluginConfiguration {
  name: String!
  version: String!
}

input NewUseCaseConfiguration {
  name: String!
  services: [NewServiceConfiguration!]!
}

input UpdateUseCaseConfiguration {
  services: [NewServiceConfiguration!]!
}

input NewServiceConfiguration {
  type: ServiceType!
  version: String!
  plugins: [NewPluginConfiguration!]!
}

input UpdateServiceConfiguration {
  version: String!
  plugins: [NewPluginConfiguration!]!
}

input NewPluginConfiguration {
  name: String!
  version: String!
}

extend type Query {
  configuration: Configuration!
  findUseCaseConfiguration(name: String!): UseCaseConfiguration!
  findServiceConfiguration(uc: String!, service: String!): ServiceConfiguration!
}

extend type Mutation {
  addUseCaseConfiguration(input: NewUseCaseConfiguration!): Configuration!
  updateUseCaseConfiguration(uc: String!, input: UpdateUseCaseConfiguration!): Configuration!
  deleteUseCaseConfiguration(uc: String!): Configuration!
  
  addServiceConfiguration(uc: String!, input: NewServiceConfiguration!): Configuration!
  updateServiceConfiguration(uc: String!, service: ServiceType!, input: UpdateServiceConfiguration!): Configuration!
  deleteServiceConfiguration(uc: String!, service: ServiceType): Configuration!
}